name: muse_ai_example
publish_to: none
description: Demonstrates how to use the muse_ai plugin.
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  chewie: ^1.3.5
  cupertino_icons: ^1.0.5
  flutter: 
    sdk: flutter
  muse_ai: 
    git: 
      url: git@github.com:SunnyApp/muse_ai
      ref: trippi_app
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
