name: muse_ai_example
publish_to: none
description: Demonstrates how to use the muse_ai plugin.
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  chewie: ^1.5.0
  cupertino_icons: ^1.0.5
  flutter: 
    sdk: flutter
  muse_ai: 
    path: /Users/ericm/aesthetika/checkout/SunnyApp/muse_ai
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
