name: muse_ai
version: 0.4.4+4
description: Integrating with MUSE.ai
repository: https://github.com/SunnyApp/muse_ai
environment: 
  sdk: '>=2.7.0 <3.0.0'
  flutter: '>=1.17.0'
dependencies: 
  pedantic: ^1.9.2
  logging: ^0.11.4
  dio: ^3.0.10
  flutter: 
    sdk: flutter
dev_dependencies: 
  flutter_test: 
    sdk: flutter
