name: muse_ai
version: 0.6.0+1
homepage: https://github.com/SunnyApp/muse_ai
description: Integrating with MUSE.ai
repository: https://github.com/SunnyApp/muse_ai
environment: 
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.17.0'
dependencies: 
  pedantic: ^1.11.1
  logging: ^1.0.2
  dio: ^4.0.0-prev3
  dartxx: 
    path: /Users/ericm/sunny/player_rank/packages/dartxx
  flutter: 
    sdk: flutter
dev_dependencies: 
  flutter_test: 
    sdk: flutter
