name: muse_ai
version: 0.6.0+1
homepage: https://github.com/SunnyApp/muse_ai
description: Integrating with MUSE.ai
repository: https://github.com/SunnyApp/muse_ai
environment: 
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.17.0'
dependencies: 
  pedantic: ^1.11.1
  logging: 1.2.0
  dio: ^5.2.0+1
  dartxx: 
    path: /Users/ericm/aesthetika/checkout/ericmartineau/dartxx
  flutter: 
    sdk: flutter
dev_dependencies: 
  flutter_test: 
    sdk: flutter
